In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("telecom_churn.csv")

In [3]:
dataset

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,-361,0
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,0
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,1
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,1
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243548,243549,Airtel,F,28,Mizoram,Kolkata,110295,2023-05-03,3,130580,28,9,4102,0
243549,243550,Reliance Jio,F,52,Assam,Kolkata,713481,2023-05-03,0,82393,80,45,7521,0
243550,243551,Reliance Jio,M,59,Tripura,Kolkata,520218,2023-05-03,4,51298,26,4,6547,0
243551,243552,BSNL,M,49,Madhya Pradesh,Kolkata,387744,2023-05-03,2,83981,80,15,1125,0
243552,243553,BSNL,F,37,Telangana,Hyderabad,139086,2023-05-04,0,144297,61,7,3384,0

In [4]:
dataset.dtypes

customer_id             int64
telecom_partner           str
gender                    str
age                     int64
state                     str
city                      str
pincode                 int64
date_of_registration      str
num_dependents          int64
estimated_salary        int64
calls_made              int64
sms_sent                int64
data_used               int64
churn                   int64
dtype: object

In [5]:
dataset.columns

Index(['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city',
       'pincode', 'date_of_registration', 'num_dependents', 'estimated_salary',
       'calls_made', 'sms_sent', 'data_used', 'churn'],
      dtype='str')

In [6]:
dataset.drop(['customer_id', 'pincode'], axis = 1, inplace=True)

In [7]:
for columnname in dataset.columns:
    print(columnname)

telecom_partner
gender
age
state
city
date_of_registration
num_dependents
estimated_salary
calls_made
sms_sent
data_used
churn

In [8]:
quan=[]
qual=[]
for columnname in dataset.columns:
    if (dataset[columnname].dtypes == 'str'):
        qual.append(columnname)
    else:
        quan.append(columnname)

In [9]:
quan

['age',
 'num_dependents',
 'estimated_salary',
 'calls_made',
 'sms_sent',
 'data_used',
 'churn']

In [10]:
qual

['telecom_partner', 'gender', 'state', 'city', 'date_of_registration']

In [11]:
descriptive=dataset

In [12]:
descriptive

,telecom_partner,gender,age,state,city,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,Reliance Jio,F,25,Karnataka,Kolkata,2020-01-01,4,124962,44,45,-361,0
1,Reliance Jio,F,55,Mizoram,Mumbai,2020-01-01,2,130556,62,39,5973,0
2,Vodafone,F,57,Arunachal Pradesh,Delhi,2020-01-01,0,148828,49,24,193,1
3,BSNL,M,46,Tamil Nadu,Kolkata,2020-01-01,1,38722,80,25,9377,1
4,BSNL,F,26,Tripura,Delhi,2020-01-01,2,55098,78,15,1393,0
...,...,...,...,...,...,...,...,...,...,...,...,...
243548,Airtel,F,28,Mizoram,Kolkata,2023-05-03,3,130580,28,9,4102,0
243549,Reliance Jio,F,52,Assam,Kolkata,2023-05-03,0,82393,80,45,7521,0
243550,Reliance Jio,M,59,Tripura,Kolkata,2023-05-03,4,51298,26,4,6547,0
243551,BSNL,M,49,Madhya Pradesh,Kolkata,2023-05-03,2,83981,80,15,1125,0
243552,BSNL,F,37,Telangana,Hyderabad,2023-05-04,0,144297,61,7,3384,0

In [13]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [14]:
descriptive

,age,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
Mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)
for columnname in quan:
    descriptive.loc["Mean",columnname]=dataset[columnname].mean()
    descriptive.loc["Median",columnname]=dataset[columnname].median()
    descriptive.loc["Mode",columnname]=dataset[columnname].mode()[0]
    descriptive.loc["Q1:25%",columnname]=np.percentile(dataset[columnname],25)
    descriptive.loc["Q2:50%",columnname]=dataset.describe()[columnname]["50%"]
    descriptive.loc["Q3:75%",columnname]=dataset.describe()[columnname]["75%"]
    descriptive.loc["Q4:100%",columnname]=dataset.describe()[columnname]["max"]
    descriptive.loc["IQR",columnname]=descriptive.loc["Q3:75%",columnname]-descriptive.loc["Q1:25%",columnname]
    descriptive.loc["1.5rule",columnname]=1.5*descriptive.loc["IQR",columnname]
    descriptive.loc["Lesser",columnname]=descriptive.loc["Q1:25%",columnname]-descriptive.loc["1.5rule",columnname]
    descriptive.loc["Greater",columnname]=descriptive.loc["Q3:75%",columnname]+descriptive.loc["1.5rule",columnname]
    descriptive.loc["min",columnname]=dataset[columnname].min()
    descriptive.loc["max",columnname]=dataset[columnname].max()
    descriptive.loc["skew",columnname]=dataset[columnname].skew()
    descriptive.loc["kurtosis",columnname]=dataset[columnname].kurtosis()
    descriptive.loc["var",columnname]=dataset[columnname].var()
    descriptive.loc["std",columnname]=dataset[columnname].std()

In [24]:
descriptive

,age,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
Mean,46.077609,1.9975,85021.137839,49.010548,23.945404,4993.186025,0.200478
Median,46.0,2.0,84990.0,49.0,24.0,4987.0,0.0
Mode,60,0,131564,86,43,8130,0
Q1:25%,32.0,1.0,52585.0,24.0,11.0,2490.0,0.0
Q2:50%,46.0,2.0,84990.0,49.0,24.0,4987.0,0.0
Q3:75%,60.0,3.0,117488.0,74.0,36.0,7493.0,0.0
Q4:100%,74.0,4.0,149999.0,108.0,53.0,10991.0,1.0
IQR,28.0,2.0,64903.0,50.0,25.0,5003.0,0.0
1.5rule,42.0,3.0,97354.5,75.0,37.5,7504.5,0.0
Lesser,-10.0,-2.0,-44769.5,-51.0,-26.5,-5014.5,0.0
Greater,102.0,6.0,214842.5,149.0,73.5,14997.5,0.0
min,18,0,20000,-10,-5,-987,0
max,74,4,149999,108,53,10991,1
skew,-0.007563,0.001801,0.000973,-0.002494,0.005314,0.003788,1.49628
kurtosis,-1.201093,-1.301356,-1.198535,-1.113612,-1.116667,-1.114216,0.238857
var,270.406102,2.002059,1406922322.819019,867.511972,217.078222,8655479.015794,0.160287
std,16.444029,1.414941,37508.963233,29.453556,14.733575,2942.019547,0.400359

In [21]:
def findoutlier():
    lesser=[]
    greater=[]
    for columnname in quan:
        if (descriptive.loc["min"][columnname]<descriptive.loc["Lesser"][columnname]):
            lesser.append(columnname)
        if (descriptive.loc["max"][columnname]>descriptive.loc["Greater"][columnname]):
            greater.append(columnname)
    return lesser,greater

In [22]:
findoutlier()

([], ['churn'])

In [25]:
def replaceoutlier():
    lesser=[]
    greater=[]
    for columnname in lesser:
        dataset.loc[dataset[columnname] < descriptive.loc["Lesser", columnname],columnname] = descriptive.loc["Lesser", columnname]
    for columnname in greater:
        dataset.loc[dataset[columnname] > descriptive.loc["Greater", columnname],columnname] = descriptive.loc["Greater", columnname]
    return lesser,greater

In [26]:
replaceoutlier()

([], [])

In [27]:
def freq_table(columnname,dataset):
    freq_table=pd.DataFrame(columns=["Unique_values","Frequency","Relative_Frequency","Cumsum"])
    freq_table["Unique_values"]=dataset[columnname].value_counts().index
    freq_table["Frequency"]=dataset[columnname].value_counts().values
    freq_table["Relative_Frequency"]=freq_table["Frequency"]/103
    freq_table["Cumsum"]=freq_table["Relative_Frequency"].cumsum()
    return freq_table

In [28]:
freq_table(columnname,dataset)

   Unique_values  Frequency  Relative_Frequency       Cumsum
0              0     194726         1890.543689  1890.543689
1              1      48827          474.048544  2364.592233